name: Publish Nuget Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'NuGet package version'
        required:  true

env:
  DOTNET_VERSION: '9.0.x'
  
jobs:
  nuget:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore Grunt

    - name: Pack
      run: dotnet pack Grunt --configuration Release /p:PackageVersion=${{ github.event.inputs.version }}
      
    - name: Push
      run: dotnet nuget push Grunt/Grunt/bin/Release/Surprenant.Grunt.${{ github.event.inputs.version }}.nupkg --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
